<<<<<<< HEAD
# Generated by Django 5.1.2 on 2025-12-18 05:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
=======
# Generated by Django 5.1.15 on 2025-12-27 14:39

import django.utils.timezone
>>>>>>> 3aa8ab6 (penambahan fitur Django admin)
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> 3aa8ab6 (penambahan fitur Django admin)
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
<<<<<<< HEAD
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
>>>>>>> 3aa8ab6 (penambahan fitur Django admin)
            ],
        ),
    ]
